export const video = {
  cV: {
    label: "cv",
    flag: "-c:v",
    options: [
      { value: "libx264", hw: "cpu" },
      { value: "h264_nvenc", hw: "nvidia" },
      { value: "h264_qsv", hw: "intel" },
      { value: "h264_amf", hw: "amd" },
      { value: "h264_vaapi", hw: "linux" },
    ],
    mode: "list",
    isImportant: false,
  },
  // profile: "high",
  // level: 4.2,
  preset: {
    label: "Preset",
    options: [
      { value: "ultrafast", hw: "UltraFast" },
      { value: "superfast", hw: "SuperFast" },
      { value: "veryfast", hw: "VeryFast" },
      { value: "faster", hw: "Faster" },
      { value: "fast", hw: "Fast" },
      { value: "medium", hw: "Medium" },
      { value: "slow", hw: "Slow" },
      { value: "slower", hw: "Slower" },
      { value: "veryslow", hw: "VerySlow" },
      { value: "placebo", hw: "Placebo" },
    ],
    mode: "list",
    isImportant: false,
  },
  // crf: 23,
  // bV: 0,
  // maxRate: 0,
  // bufSize: 0,
  // pixFmt: "yuv420p",
  // r: 30,
  // g: 60,
  // keyintMin: 60,
  // scThreshold: 0,
};
